---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by root.
--- DateTime: 2024/12/1 下午7:58
-- lua -i
-- lua -i

a=2
a1=2
_demo= 2
-- [[


-- ]]

local a  = 8
print(a)

--while(true)
--do
--    print("====")
--end

for i = 10,1,-1
do
    print(i)
end

function f(x)
    print("function")
    return x*2
end
for i=1,f(5) do print(i)
end

function f(x)
    print("function")
    return x*2
end
for i=1,f(5) do print(i)
end