// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.2
// - protoc             v5.28.3
// source: api/helloworld/v1/auth.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAuthAuthCallback = "/api.helloworld.v1.Auth/AuthCallback"
const OperationAuthSignIn = "/api.helloworld.v1.Auth/SignIn"

type AuthHTTPServer interface {
	AuthCallback(context.Context, *CreateAuthRequest) (*CreateAuthReply, error)
	SignIn(context.Context, *CreateAuthRequest) (*CreateAuthReply, error)
}

func RegisterAuthHTTPServer(s *http.Server, srv AuthHTTPServer) {
	r := s.Route("/")
	r.GET("/helloworld/login", _Auth_SignIn0_HTTP_Handler(srv))
	r.GET("/helloworld/callback", _Auth_AuthCallback0_HTTP_Handler(srv))
}

func _Auth_SignIn0_HTTP_Handler(srv AuthHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAuthRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthSignIn)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SignIn(ctx, req.(*CreateAuthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAuthReply)
		return ctx.Result(200, reply)
	}
}

func _Auth_AuthCallback0_HTTP_Handler(srv AuthHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAuthRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthAuthCallback)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AuthCallback(ctx, req.(*CreateAuthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAuthReply)
		return ctx.Result(200, reply)
	}
}

type AuthHTTPClient interface {
	AuthCallback(ctx context.Context, req *CreateAuthRequest, opts ...http.CallOption) (rsp *CreateAuthReply, err error)
	SignIn(ctx context.Context, req *CreateAuthRequest, opts ...http.CallOption) (rsp *CreateAuthReply, err error)
}

type AuthHTTPClientImpl struct {
	cc *http.Client
}

func NewAuthHTTPClient(client *http.Client) AuthHTTPClient {
	return &AuthHTTPClientImpl{client}
}

func (c *AuthHTTPClientImpl) AuthCallback(ctx context.Context, in *CreateAuthRequest, opts ...http.CallOption) (*CreateAuthReply, error) {
	var out CreateAuthReply
	pattern := "/helloworld/callback"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuthAuthCallback))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AuthHTTPClientImpl) SignIn(ctx context.Context, in *CreateAuthRequest, opts ...http.CallOption) (*CreateAuthReply, error) {
	var out CreateAuthReply
	pattern := "/helloworld/login"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuthSignIn))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
